version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: events_mongodb
    environment:
      # MONGO_INITDB_ROOT_USERNAME: event
      # MONGO_INITDB_ROOT_PASSWORD: event12345
      MONGO_INITDB_DATABASE: events_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - events-data:/data/db
volumes:
  events-data:
